### ISSUE TITLE
Small Caps font for the letter ṅ does not show a small cap but rather a lowercase letter

### ISSUE THREAD

**Issue by kleinbottle** [notofonts/latin-greek-cyrillic#413] opened 2023-04-11 18:04 UTC
`\textsc{Vedāṅga}` in `LaTeX` shows up as ![small-caps](https://user-images.githubusercontent.com/193362/231250353-8c3c75fc-cba4-4b03-855f-2953de30698b.png)

**Comment by bsoap-cat** [comment] 2023-09-21 00:03
then just use U+274 and U+307

**Comment by moyogo** [comment] 2023-09-21 21:14
Duplicate of #160.

**Closed** 2023-09-21 21:14 UTC

**Comment by moyogo** [comment] 2023-09-21 21:16
> then just use U+274 and U+307

@bsoap-cat this wouldn't look right. ɴ has x-height, small-scale are slightly taller, and it has different semantics.

**Comment by bsoap-cat** [comment] 2023-09-23 21:31
> > then just use U+274 and U+307
> 
> @bsoap-cat this wouldn't look right. ɴ has x-height, small-scale are slightly taller, and it has different semantics.

I already knew that, I just thought it would be a good idea to just use the combinations I had mentioned. (also congrats on getting the lambdas accepted for a future unicode update)

**Comment by kleinbottle** [comment] 2024-01-13 13:35
> then just use U+274 and U+307

Did you mean U+0274: [“ɴ” U+0274 Latin Letter Small Capital N Unicode Character](https://www.compart.com/en/unicode/U+0274) and Unicode Character “◌̇” (U+0307)?

How would I apply what you have suggested within a LaTeX document? AFAICT, I can define a single Unicode character U+wxyz as `^^^^wxyz` in LaTeX but am unsure of combining diacritics and letters.

Will the font itself be patched in a later release?

**Comment by kleinbottle** [comment] 2024-01-14 14:52
> then just use U+274 and U+307

In `typst` I used `#text(font: "Noto Serif", smallcaps("Vedāɴ̇ga"))` and got the desired PDF. I trsut the same will work with LaTeX.
