### ISSUE TITLE
Noto Serif U+0060 does not shape correctly

### ISSUE THREAD

**Issue by chrissimpkins** [notofonts/latin-greek-cyrillic#428] opened 2023-05-08 16:31 UTC
User report:

Noto Serif is rendering backticks (`) as combining diacritics, when they should not be according to the unicode standard.

Expected behavior: When I press the key on the top left of my keyboard next to the "1", it should insert the following character: <`> (UTF-8 0060) which should behave as an independent character (i.e. appear multiple times if I press it multiple times, not combine with the character after it.)

Observed behavior: The character acts instead like the combining diacritic UTF 0300, merging with the character that follows it.

---

I can reproduce the findings in this report with the production Noto Serif fonts served on fonts.google.com as of May 8, 2023.

<img width="1989" alt="BxqqhNNHgjN4ZF6" src="https://user-images.githubusercontent.com/4249591/236878375-cd89bc9a-55f9-4eae-8624-fd06413f3c04.png">

I cannot reproduce it in the Noto Sans family.

[280314224]

**Comment by simoncozens** [comment] 2023-05-09 07:03
Duplicate of #11.

**Closed by simoncozens** 2023-05-09 07:03 UTC

**Comment by simoncozens** [comment] 2023-05-09 07:05
(And will be fixed when https://github.com/google/fonts/pull/6134 is merged; it has been approved, so we can't be long off...)

**Comment by chrissimpkins** [comment] 2023-05-09 17:22
Out of interest, what was the fix for this issue?

**Comment by moyogo** [comment] 2023-05-10 05:29
@chrissimpkins Components and anchors propagation.

**Comment by moyogo** [comment] 2023-05-10 08:26
@chrissimpkins Actually that wasn’t it, it was in the wrong GDEF glyph class, in the Mark class.

**Comment by chrissimpkins** [comment] 2023-05-10 11:34
Thank you Denis!
