### ISSUE TITLE
ss04 not available in Noto Serif

### ISSUE THREAD

**Issue by brunood1** [notofonts/latin-greek-cyrillic#437] opened 2023-06-24 05:12 UTC
The stylistic set 04 (non-descending uppercase J) that is available in Noto Sans is not available in Noto Serif
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/97195236/04574f75-54c5-4d65-b4c6-306ac09f8bbc)

**Comment by berrymot** [comment] 2023-06-24 08:31
(now I'm wondering what ss06 does)

**Comment by simoncozens** [comment] 2023-06-24 09:49
> The stylistic set 04 (non-descending uppercase J) that is available in Noto Sans is not available in Noto Serif

This is a duplicate of #120.

> (now I'm wondering what ss06 does)

Accented Greek small capitals

**Closed by simoncozens** 2023-06-24 09:49 UTC
