### ISSUE TITLE
Incorrect vertical alignment of hyphen-minus sign

### ISSUE THREAD

**Issue by dm-u** [notofonts/latin-greek-cyrillic#473] opened 2024-04-26 06:10 UTC
### Title 

Incorrect vertical alignment of hyphen-minus sign

### Font 

NotoSansMono[wdth,wght].ttf

### Where the font came from, and when

Site: https://cdn.jsdelivr.net/gh/notofonts/notofonts.github.io/fonts/NotoSansMono/unhinted/variable/NotoSansMono[wdth,wght].ttf

Date: 2024-04-26

### Font Version

2.014

### OS name and version

Windows 11 23H2

### Application name and version

Visual Studio Code

### Issue

Type '->', '+-'. Those symbols must be aligned vertically. But symbol '-' lower than symbols '>', '<' or '+'.

### Character data

    -> <=>

### Screenshot

Noto Sans Mono:
![Screenshot 2024-04-26 090812](https://github.com/notofonts/latin-greek-cyrillic/assets/1056017/f1c3eddc-63c0-4828-8967-6dff3c4d2213)

Soruce Code Pro:
![Screenshot 2024-04-26 090921](https://github.com/notofonts/latin-greek-cyrillic/assets/1056017/a2cdf655-0c92-4c77-9987-aae31930f59e)

Consolas:
![Screenshot 2024-04-26 090950](https://github.com/notofonts/latin-greek-cyrillic/assets/1056017/f9e21c98-fd11-4c28-82c0-ef86f19de485)

**Comment by simoncozens** [comment] 2024-04-26 06:18
Duplicate of #472. The hyphen-minus is well aligned against text, but not symbols.

**Closed by simoncozens** 2024-04-26 06:18 UTC
