### ISSUE TITLE
[Mono ExtraCondensed] Some symbols are displayed at full width

### ISSUE THREAD

**Issue by elvis-hrvat** [notofonts/latin-greek-cyrillic#441] opened 2023-08-29 16:22 UTC
## Defect Report

> Noto fonts can be obtained from https://notofonts.github.io/
> If you find a problem with a released font, then please use this template to file a defect report.
> Before filing your report, please check if the issue has been fixed in the latest development build. You can get development builds by finding the font family on https://notofonts.github.io/ and following the link to "Development builds".

### Title 
Some symbols are displayed at full width

### Font 
NotoSansMono-ExtraCondensed.ttf

### Where the font came from, and when
Site: https://notofonts.github.io/latin-greek-cyrillic/fonts/NotoSansMono/unhinted/ttf/NotoSansMono-ExtraCondensed.ttf
Date: 2023-08-30

### Font Version
2.013; ttfautohint (v1.8.4.7-5d5b)

### OS name and version
Arch Linux

### Application name and version
[xed](https://archlinux.org/packages/extra/x86_64/xed/), [Joplin](https://aur.archlinux.org/packages/joplin-appimage), [Tilix](https://archlinux.org/packages/extra/x86_64/tilix/)

### Issue
U+25A2, U+25A3 are displayed in full width while U+25A0 and U+25B2 are displayed in half width.

This prevents the terminal emulator from displaying the character widths correctly.

### Character data
U+25A2, U+25A3, U+25B3, etc.

### Screenshot
![xed](https://github.com/notofonts/latin-greek-cyrillic/assets/142690244/b1976963-92cc-493c-96f4-0c086b1f0453)

### Harfbuzz hb-view and hb-shape
  These are part of the HarfBuzz distribution and can help isolate if an issue is in the app/OS, shaping engine, or font.
  * hb-view renders the text with the exact font (for example, to see how ligatured characters shape) using your installed version of HarfBuzz.

For example:
```
  hb-view --font-file {path to font} --text-file {path to text file} --output-file '{sample}.png'
```
![harfbuzz](https://github.com/notofonts/latin-greek-cyrillic/assets/142690244/15b3bf83-a935-47a8-9dd2-491b26de6b6a)

* hb-shape shows glyph selection and positioning

### Fontview
  * Fontview displays the text.

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by simoncozens** [comment] 2023-08-31 17:13
This is kind of a duplicate of #234. Noto Sans Mono is not monospaced; the question is whether or not that really is a problem.

**Closed by simoncozens** 2023-08-31 17:13 UTC
